US914108: Version Currency: JUnit 5 migration
CAFapi/caf-common pull request #114
Opened 2024-07-02 10:24 UTC by raghavendran-gopalakrishnan

https://internal.almoctane.com/ui/entity-navigation?p=131002/6001&entityType=work_item&id=914108

2024-07-02 10:26 UTC, buildmachine-sou-jenkins2 commented
A developer build has not yet been created for this branch. Click [here](https://sou-jenkins2.swinfra.net/job/Create-New-Build/parambuild/?GITHUB_SERVER=github.com&GITHUB_ORGANISATION=CAFapi&REPO_NAME=caf-common&BRANCH_NAME=914108) to go ahead and create the build...

2024-07-02 10:29 UTC, buildmachine-sou-jenkins2 commented
CI Build Link:
https://sou-jenkins2.swinfra.net/job/CAFapi/job/CAFapi~caf-common~914108~CI

2024-07-03 20:13 UTC, dermot-hardy requested changes
The main branch build shows 42 tests but your build only shows 41:

- https://sou-jenkins2.swinfra.net/job/CAFapi/job/CAFapi~caf-common~develop~CI/88/testReport/
- https://sou-jenkins2.swinfra.net/job/CAFapi/job/CAFapi~caf-common~914108~CI/2/testReport/

Why have we dropped a test?

@michael-bryson We're not expecting to lose tests in the migration to JUnit 5.  I just wanted to point it out as it will be an important thing to verify when this ticket gets into QA.

2024-07-03 20:13 UTC, dermot-hardy commented on pom.xml
> +                <groupId>org.junit.jupiter</groupId>
Dependency management should be in alphabetical order.

2024-07-04 10:36 UTC, raghavendran-gopalakrishnan commented
> The main branch build shows 42 tests but your build only shows 41:
> 
> * https://sou-jenkins2.swinfra.net/job/CAFapi/job/CAFapi~caf-common~develop~CI/88/testReport/
> * https://sou-jenkins2.swinfra.net/job/CAFapi/job/CAFapi~caf-common~914108~CI/2/testReport/
> 
> Why have we dropped a test?
> 
> @michael-bryson We're not expecting to lose tests in the migration to JUnit 5. I just wanted to point it out as it will be an important thing to verify when this ticket gets into QA.

Looks like surefire is using 

> Using auto detected provider org.apache.maven.surefire.junitplatform.JUnitPlatformProvider

instead of 
> Using auto detected provider org.apache.maven.surefire.testng.TestNGProvider

So the test was not picked up, I will look into this.

2024-07-04 11:01 UTC, raghavendran-gopalakrishnan commented
> Looks like surefire is using
> 
> > Using auto detected provider org.apache.maven.surefire.junitplatform.JUnitPlatformProvider
> 
> instead of
> 
> > Using auto detected provider org.apache.maven.surefire.testng.TestNGProvider
> 
> So the test was not picked up, I will look into this.

`junit-platform-commons` is included as transitive dependency by which `JUnitPlatformProvider` takes priority over `TestNGProvider`.

2024-07-04 11:22 UTC, raghavendran-gopalakrishnan commented
Earlier dropped test is now picked up:
![image](https://github.com/CAFapi/caf-common/assets/11929432/69fefe1c-09f6-4590-969f-8b30114897f8)

2024-07-04 15:24 UTC, dermot-hardy requested changes
Just scrap the `util-testing` module and move the `MultiThreadTestUtil` class into the test code of `util-process-identifier`, since that is the only place that it is used.  (It may be surprising but scrapping this module is not a breaking change.)

2024-07-05 12:32 UTC, dermot-hardy approved these changes

2024-07-05 12:32 UTC, dermot-hardy commented on util-process-identifier/src/test/java/com/hpe/caf/util/processidentifier/MultiThreadTestUtil.java
> +package com.hpe.caf.util.processidentifier;
Does the class still need to be `public` in the new location?

2024-07-08 06:24 UTC, merged