Add db create
CAFapi/caf-common pull request #37
Opened 2018-03-20 22:51 UTC by rob-duewer

Ready for review

2018-03-20 23:21 UTC, dermot-hardy requested changes
The script itself seems fine but I think it should be put it straight into the [CAFapi/opensuse-tini-image](https://github.com/CAFapi/opensuse-tini-image) repository rather than having it here.  The certificate scripts are only in here for historical reasons and it's a pain because if they change there are more projects to release.  Create a `startup.d` directory in `opensuse-tini-image/src/main/docker/startup/` and put it in there.  The Dockerfile may also need to be adjusted (although looking at it I don't think it does).  And the release notes and readme should be updated for the new functionality.

2018-03-20 23:21 UTC, dermot-hardy commented on create-db-script/check-create-pgdb.sh
> +extension=$([[ "$scriptName" = *.* ]] && echo ".${scriptName##*.}" || echo '')
`extension` variable appears not to be used

2018-03-20 23:21 UTC, dermot-hardy commented on create-db-script/check-create-pgdb.sh
> +# ----------Variable Section-----------#
Copyright header required - see [here](https://github.com/CAFapi/opensuse-tomcat-image/blob/v3.0.0/src/main/docker/startup.d/setup-tomcat-ssl-cert.sh) for example.

2018-03-21 19:47 UTC, rob-duewer commented
Cancelling pull request.  Will create a new one with changes against the opensuse-tini-image project instead.

2018-03-21 19:47 UTC, closed without merging