SCMOD-7738 Updating KeyView Java API Version [DO NOT MERGE]
CAFapi/caf-common pull request #51
Opened 2019-10-14 15:28 UTC by rorytorneymf

IMPORTANT: DO NOT MERGE - This merge needs to be coordinated with the merge of the new keyview-container and the worker-textextract.

Updating caf-common to point to the new KeyView 12.4.0 Java
API dependency located here:

http://sounxgbld02.englab.local:8081/artifactory/company-central/com/microfocus/caf/keyview/keyview-api-12.4.0/1.0.0-SNAPSHOT/

This new dependency is now uploaded to the above location
by this project:

https://github.houston.softwaregrp.net/caf/keyview-lib-deploy

2019-10-14 15:36 UTC, dermot-hardy approved these changes

2019-10-14 15:37 UTC, dermot-hardy commented
Is this the only change required?  This is just the dependency management section.

2019-10-14 15:41 UTC, rorytorneymf commented
> Is this the only change required? This is just the dependency management section.

In this project (caf-common) I believe its the only change required - this is pulled into the worker-textextract - there will be more changes in that project (not ready for PR yet).

2019-10-14 17:00 UTC, dermot-hardy requested changes
In that case this dependency should be removed from here altogether rather than being updated.  Only dependencies used by `caf-common` projects should be listed in its dependency management section.

2019-10-15 08:49 UTC, rorytorneymf commented
> In that case this dependency should be removed from here altogether rather than being updated. Only dependencies used by `caf-common` projects should be listed in its dependency management section.

Removed keyview dependency now from caf-common.

2019-10-15 11:11 UTC, dermot-hardy approved these changes

2019-10-23 16:29 UTC, merged