Initial drafts of readmes for CAF-1915
CAFapi/caf-common pull request #6
Opened 2017-01-03 10:17 UTC by conalsmith49

Initial drafts completed 23rd December.

2017-01-04 15:06 UTC, conalsmith49 commented
I've made some more changes. 

These all should be reviewed, but specifically:
- util-moduleloader
- container-cert-script
- caf-api - perhaps a better introduction paragraph

2017-01-09 11:19 UTC, glucy reviewed
Not sure the "Usage" and "Maintainer" sections are required.  Will let @dermot-hardy decide.  Otherwise one minor correction required.

2017-01-09 11:19 UTC, glucy commented on util-naming/README.md
> +A class that is similar to java.naming.Name, but is iterable. A Name is a tokenized character String, delimited by forward-slashes.
Should this not be javax.naming.Name?

2017-01-09 17:10 UTC, conalsmith49 commented
Changed java to javax, as the mentioned library does not exist - typo.

2017-01-09 17:28 UTC, glucy approved these changes
I will push this through tomorrow unless someone else reviews: @dermot-hardy, @andyreidz

2017-01-10 22:20 UTC, dermot-hardy requested changes

2017-01-10 22:20 UTC, dermot-hardy commented on caf-api/README.md
> +CAF-API is a sub module of CAF-Common and contains essential interfaces, exceptions, configurations and classes used in creating [CAF](http://cafapi.github.io/) services and frameworks. These interfa
I don't really like "promotes code reuse" in this sentence - can we say "provide a layer of abstraction to allow for different implementations".  Then talk about how multiple datastores can be used with CAF, or you could use different codecs as required (Json or Xml for example).

2017-01-10 22:20 UTC, dermot-hardy commented on caf-api/README.md
> +- BootstrapConfiguration: A method of providing a basic initial startup configuration.
I don't like the word 'method' here - this is an interface not a method.  Just say "Provides the initial startup configuration".

2017-01-10 22:20 UTC, dermot-hardy commented on caf-api/README.md
> +- ConfigurationException: Thrown when there is a problem with the ConfigurationSource module.
with the configuration, not with the ConfigurationSource module

2017-01-10 22:20 UTC, dermot-hardy commented on caf-api/README.md
> +- ConfigurationSource: A ConfigurationSource is intended to provide an implementation-agnostic method of retrieving application-specific configuration.
Don't say "is intended to provide" - it sounds like it's not provided

2017-01-10 22:20 UTC, dermot-hardy commented on caf-api/README.md
> +## Usage
Remove the Usage section - also never encourage people to parent on caf-parent / caf-common.  These are for our use only.

2017-01-10 22:20 UTC, dermot-hardy commented on caf-api/README.md
> +- QuietResource: Utility class for use with try-with-resources, for classes where the close operation may throw an exception, but this is not a useful check. @param <T> the class to close quietly
What does "@param the class to close quietly" mean?

2017-01-10 22:20 UTC, dermot-hardy commented on caf-parent/README.md
> +Using this POM file as the parent for your project will ensure dependency versions and scopes are kept consistent and compatible with all other [CAF](http://cafapi.github.io/) components, services an
This comment is somewhat irrelevant since I've removed caf-parent from the caf-common project, so you won't be able to merge this file anyway.

But just for the record we should not encourage the use of any of our POMs as somebody else's parent.  If we want to provide that functionality then we would do it through the \<dependencyManagement\> section.  Take a look at the example worker - https://github.com/WorkerFramework/worker-framework/blob/develop/worker-example/worker-example/pom.xml - the worker-framework dependencies are imported using dependencyManagement; it does not use worker-framework as a parent (that would make it too brittle).

2017-01-10 22:20 UTC, dermot-hardy commented on container-cert-script/README.md
> +The container cert script contains CAcert installation scripts for installing Java security certificates primarily for use in [CAF](http://cafapi.github.io/) service development and installation of t
They are not just Java certificates - the install-ca-cert.sh installs into the OS certificate store.

2017-01-10 22:20 UTC, dermot-hardy commented on container-cert-script/README.md
> +If your project's parent pom is [CAF Parent](../caf-parent) then add the dependency below, otherwise specify a version number.
The usage is useful here but it needs to be updated in line with my previous comments.

2017-01-10 22:20 UTC, dermot-hardy commented on util-jerseycompat/README.md
> +If your project's parent pom is [CAF Parent](../caf-parent) then add the dependency below, otherwise specify a version number.
First part of the usage needs to be removed

2017-01-10 22:20 UTC, dermot-hardy commented on util-moduleloader/README.md
> +If your project's parent pom is [CAF Parent](../caf-parent) then add the dependency below, otherwise specify a version number.
Drop the CAF Parent reference

2017-01-10 22:20 UTC, dermot-hardy commented on util-moduleloader/README.md
> +
Explain the advantage of using this over using Java ServiceLoader directly.

2017-01-10 22:20 UTC, dermot-hardy commented on util-naming/README.md
> +## Project Usage
Remove this section

2017-01-10 22:20 UTC, dermot-hardy commented on util-naming/README.md
> +- `public Name(final List<String> components)`
Perhaps a code snippet would help here.

2017-01-10 22:20 UTC, dermot-hardy commented on util-ref/README.md
> +Utility wrapper for allowing data to potentially be within a message or located on a remote DataStore. The acquire(ObjectSource) method allows transparent method of obtaining an InputStream to the da
The `acquire(ObjectSource)` should be surrounded with back-ticks.

2017-01-10 22:20 UTC, dermot-hardy commented on util-ref/README.md
> +Utility wrapper for allowing data to potentially be within a message or located on a remote DataStore. The acquire(ObjectSource) method allows transparent method of obtaining the wrapped data, which
"allowing data" is the same way that `ReferencedData` was described - should this not be "allowing a serialised object" or something like that?

2017-01-10 22:20 UTC, dermot-hardy commented on util-ref/README.md
> +If your project's parent pom is [CAF Parent](../caf-parent) then add the dependency below, otherwise specify a version number.
Remove CAF Parent avocation.

2017-01-12 12:46 UTC, conalsmith49 commented
I have made review comments, @dermot-hardy could you take a look at the comments I have mentioned you in to make sure you are happy with the changes?

2017-01-12 14:57 UTC, merged