SCMOD-12755: Allow CA Certificates to be installed as non-root user
CAFapi/caf-common pull request #68
Opened 2021-03-09 13:17 UTC by dgibson-microfocus

2021-03-09 13:20 UTC, buildmachine-sou-jenkins2 commented
A developer build has not yet been created for this branch. Click [here](http://sou-jenkins2.swinfra.net:8080/job/Create-New-Build/parambuild/?GITHUB_SERVER=github.com&GITHUB_ORGANISATION=CAFapi&REPO_NAME=caf-common&BRANCH_NAME=SCMOD-12755) to go ahead and create the build...

2021-03-09 13:26 UTC, buildmachine-sou-jenkins2 commented
CI Build Link:
http://sou-jenkins2.swinfra.net:8080/job/CAFapi/job/CAFapi~caf-common~SCMOD-12755~CI

2021-03-09 20:05 UTC, dermot-hardy reviewed
Safe to say I didn't understand 90% of that.  You'll have to talk me through it.

2021-03-09 20:05 UTC, dermot-hardy commented on container-cert-script/install-ca-cert.sh
> +    cp -R /tmp/ssl/ca-certificates/openssl/* /var/lib/ca-certificates/openssl/
I don't really know what this is doing to comment on it but I presume it can't be directly done against the files in `/var/lib/ca-certificates/openssl/`?

2021-03-09 20:05 UTC, dermot-hardy commented on container-cert-script/install-ca-cert.sh
>              copy_certs "Debian" /usr/local/share/ca-certificates
I presume you've tested none of this with "Debian".  We should just drop support for the non-OpenSUSE distros that we're not testing.

2021-03-09 20:05 UTC, dermot-hardy commented on container-cert-script/install-ca-cert.sh
> +      mv -Tv --backup=numbered "$etccertsdir" "$etccertsdir.old"
What's going on with the indenting here?

2021-03-09 20:05 UTC, dermot-hardy commented on container-cert-script/install-ca-cert.sh
> +    for i in "$@"; do
I only see you calling this once and you're not passing any arguments?  Is there something about bash syntax I'm not understanding here?

2021-03-09 23:41 UTC, rob-duewer requested changes
I'm actually not a fan of this approach at all.  Trying to undermine the distribution's native certificate bundle extension function (update-ca-certificates in the case of OpenSUSE, others native to each distro otherwise), seems like a significant misstep.

Did you already look earlier in the base image creation granting specific sudo privilege to just the elevated command(s so you can stay multi-distro) you need?

Earlier in the base image build, just add a sudoers.d dropin file for your "run as" user, like:  (And if you don't want to call with the explicit path, you can grant to just update-ca-certificates, but it's a little riskier maybe.

\<user\>   ALL=/usr/sbin/update-ca-certificates

You might also need to explicitly allow elevate the cp from the incoming sandbox dir to the distro appropriate FS target.  But you can do it in the same drop in, since you can provide a whole list of accepted sudo'd commands in the single definition.

Then you don't have to change any logic in the shell, try to rig the manipulation of a file that is supposed to be always system generated, etc.  And it has the luxury, if this script was being used somewhere else (outside of a container, in a container which is being called as root, whatever), it will still happily keep working.  (IE by definition, root can call any command with sudo; no worries.)  You can always catch the error on a sudo return and log that failure out.  Or if you want to be really fancy, check at the start of the script for the specific actions you would need (sudo -l should tell you what your current user has) and preemptively bail out and log if for some reason its not there.

Or did you already run this model down and discount it for some reason I'm not thinking of?

Also, it's not in this PR, but if you need to control the java system CA bundle via our other pre-init script; we should look to do that same selective sudo perm there as well.  Should be very similar.

2021-03-10 00:57 UTC, dermot-hardy commented
These ideas are worth exploring if they haven't been.  My gut feeling is that where they may come unstuck is with the registration of the user as a sudoer, given that the requirement is to be able to run as an arbitrary user, i.e. where it is not known at image build time what the user will be.  Can ranges of users be made sudoers?

2021-03-10 08:52 UTC, dgibson-microfocus commented
I was unaware this approach was available. We could use a group/groups rather than specific users in the rule definitions to allow the container being run as arbitrary users, though obviously they'd need to be a member of said group.

2021-03-10 15:40 UTC, dgibson-microfocus commented
I'm closing this PR as it's no longer needed with the sudoers.d approach. The changes will be made in follow up PRs against the base images.

2021-03-10 15:40 UTC, closed without merging